name: lint-test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: shellcheck
        run: shellcheck scripts/*.sh

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5

      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8
        with:
          version: latest
  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}"  >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: false
          tags: |
            ezproxy-url-checker:${{steps.extract_branch.outputs.branch}}

      - name: Run tests
        shell: bash
        run: |-
          ./scripts/generate-files.sh $(pwd)/fixtures
          CONTAINER=$(docker run \
            --rm \
            -d \
            -v $(pwd)/config:/app/config \
            ezproxy-url-checker:${{steps.extract_branch.outputs.branch}})
          docker logs $CONTAINER
          docker exec $CONTAINER /bin/bash /app/scripts/test.sh
          docker stop $CONTAINER
