name: lint-test

on:
  push:
    branches:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}"  >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: |
            ezproxy-url-checker:${{steps.extract_branch.outputs.branch}}

      - name: Start service
        shell: bash
        run: |-
          cp fixtures/*.txt config/
          docker run --rm -d -p 8888:8888 ezproxy-url-checker:${{steps.extract_branch.outputs.branch}}

      - name: Run tests
        shell: bash
        run: |-
          ./scripts/test.sh
